openapi: 3.0.3
info:
  title: Auth Service API
  description: |
    Microservicio de autenticacion y gestion de usuarios.
    **Responsable**: Integrante 1
    **Rama Git**: feature/auth-service
  version: 1.0.0
  contact:
    name: Equipo Auth

servers:
  - url: http://localhost:8081/api/v1
    description: Local development
  - url: http://auth-service:8081/api/v1
    description: Docker/K8s internal

tags:
  - name: auth
    description: Autenticacion y tokens
  - name: users
    description: Gestion de usuarios

paths:
  /auth/login:
    post:
      tags: [auth]
      summary: Iniciar sesion
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Credenciales invalidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/register:
    post:
      tags: [auth]
      summary: Registrar nuevo usuario
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '409':
          description: Email ya existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/refresh:
    post:
      tags: [auth]
      summary: Refrescar token
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Token refrescado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Token invalido o expirado

  /auth/validate:
    post:
      tags: [auth]
      summary: Validar token (uso interno entre microservicios)
      operationId: validateToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateTokenRequest'
      responses:
        '200':
          description: Token valido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenValidationResponse'
        '401':
          description: Token invalido

  /auth/password/forgot:
    post:
      tags: [auth]
      summary: Solicitar restablecimiento de contraseña
      operationId: requestPasswordReset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
      responses:
        '200':
          description: Solicitud procesada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /auth/password/verify:
    post:
      tags: [auth]
      summary: Verificar codigo de restablecimiento
      operationId: verifyPasswordReset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetVerifyRequest'
      responses:
        '200':
          description: Codigo verificado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Codigo inválido o expirado

  /auth/password/reset:
    post:
      tags: [auth]
      summary: Restablecer contraseña
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirmRequest'
      responses:
        '200':
          description: Contraseña actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Token inválido o expirado

  /users/me:
    get:
      tags: [users]
      summary: Obtener usuario actual
      operationId: getCurrentUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Datos del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

  /users/{id}:
    get:
      tags: [users]
      summary: Obtener usuario por ID (admin o interno)
      operationId: getUserById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Usuario no encontrado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: usuario@hotel.com
        password:
          type: string
          format: password
          minLength: 6

    RegisterRequest:
      type: object
      required: [username, email, password]
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 6
        telefono:
          type: string
          maxLength: 20

    RefreshTokenRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string

    ValidateTokenRequest:
      type: object
      required: [token]
      properties:
        token:
          type: string

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        tokenType:
          type: string
          default: Bearer
        expiresIn:
          type: integer
          description: Segundos hasta expiracion
        user:
          $ref: '#/components/schemas/UserResponse'

    TokenValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
        userId:
          type: integer
          format: int64
        email:
          type: string
        role:
          type: string

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        telefono:
          type: string
        role:
          type: string
          enum: [USER, ADMIN]
        activo:
          type: boolean
        fechaCreacion:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string

    MessageResponse:
      type: object
      properties:
        message:
          type: string
    PasswordResetRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email

    PasswordResetVerifyRequest:
      type: object
      required: [email, code]
      properties:
        email:
          type: string
          format: email
        code:
          type: string
          minLength: 6
          maxLength: 6

    PasswordResetConfirmRequest:
      type: object
      required: [email, code, newPassword]
      properties:
        email:
          type: string
          format: email
        code:
          type: string
          minLength: 6
          maxLength: 6
        newPassword:
          type: string
          format: password
          minLength: 6
